package net.mmly.openminemap.enums;

public enum TileUrlErrorType {
    NO_ERROR,
    MALFORMED_JSON_FILE,
    NULL_TILE_URL,
    NULL_VALUE,
    MALFORMED_SOURCE_URL,
    MALFORMED_ATTRIBUTION_LINK,
    INVALID_SOURCE_URL_BRACKET_PLACEMENT,
    INVALID_ATTRIBUTION_BRACKET_PLACEMENT,
    MISMATCHED_ATTRIBUTION_LINKS,
    MISSING_X_POSITION_FIELD,
    MISSING_Y_POSITION_FIELD,
    MISSING_ZOOM_FIELD,
}